### ISSUE TITLE
Dịch Tiếng Việt

### ISSUE THREAD

**Issue by lkamazaezuzemedium** [MicrosoftTranslator/Local-Feature-Android#8]

**Comment by chriswendt1** [comment]
To translate from or to Vietnamese, use language code "vi" as tyhe "from" or the "to" language in the Translator API.

**Comment by lkamaza** [comment]
> Để dịch từ hoặc sang tiếng Việt, sử dụng mã ngôn ngữ "vi" là tyhe "từ" hoặc ngôn ngữ "sang" trong API dịch.

Cảm ơn 😊

**Comment by lkamaza** [comment]
#10 thks
